#!/bin/bash

set -a

ESSID_HIGH_SYMBOL=${ESSID_HIGH_SYMBOL:-' '}

ESSID_MED_THRESH=${ESSID_MED_THRESH:--50}
ESSID_MED_SYMBOL=${ESSID_MED_SYMBOL:-' '}

ESSID_LOW_THRESH=${ESSID_LOW_THRESH:--70}
ESSID_LOW_SYMBOL=${ESSID_LOW_SYMBOL:-' '}

ESSID_NOT_AVAILABLE_SYMBOL=${ESSID_NOT_AVAILABLE_SYMBOL:-' '}

INTERFACE="${INTERFACE:-wlp3s0}"

OUTPUT=$(iw dev $INTERFACE link)

SSID=$(echo "$OUTPUT" | grep -Poe '(?<=SSID: ).*')
dBm=$(echo "$OUTPUT" | grep -Poe '-\d{2}(?= dBm)')

function print_format {
    echo "$1" | envsubst '${SYMB}${dBm}${SSID}'
}

SYMB=$ESSID_NOT_AVAILABLE_SYMBOL
[[ -n "$dBm" ]] || (print_format '${SYMB}' && exit 1)

SYMB=$ESSID_HIGH_SYMBOL
[[ $dBm -le $ESSID_MED_THRESH ]] && SYMB=$ESSID_MED_SYMBOL
[[ $dBm -le $ESSID_LOW_THRESH ]] && SYMB=$ESSID_LOW_SYMBOL

print_format "$LONG_FORMAT"
print_format "$SHORT_FORMAT"
