#!/bin/bash

FAILED_COLOR=${FAILED_COLOR:-red}
INACTIVE_COLOR=${INACTIVE_COLOR:-orange}
FORMAT=${FORMAT:-$UNIT_NAME}

if [[ -n $ACTIVE_COLOR ]]
then
	ACTIVE_COLOR=" color='$ACTIVE_COLOR'"
fi

status="systemctl status $UNIT_NAME"
command="systemctl"

if [[ $USER_UNIT == "true" ]]
then
	status="${status} --user"
	command="${command} --user"
else
	command="sudo ${command}"
fi

status=$($status | head -n3 | tail -n1 | awk '{ print $2 }')

if [[ $status == "active" ]]
then
	echo "<span${ACTIVE_COLOR}>$FORMAT</span>"
	command="${command} stop"
else
	if [[ $status == "failed" ]]
	then
		echo "<span color='$FAILED_COLOR'>$FORMAT</span>"
	elif [[ $status == "inactive" ]]
	then
		echo "<span color='$INACTIVE_COLOR'>$FORMAT</span>"
	fi
	command="${command} start"
fi

case "$BLOCK_BUTTON" in
  1|2|3) 
		$command $UNIT_NAME
esac
